FROM --platform=linux/amd64 golang:1.22.5

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o consumer/consumer ./consumer

COPY wait-for-it.sh ./
RUN chmod +x wait-for-it.sh

CMD ["./wait-for-it.sh", "kafka:9092", "--", "./consumer/consumer"]
