# Use Debian-based official Golang image with platform specification
FROM --platform=linux/amd64 golang:1.22.5

# Set working directory
WORKDIR /app

# Copy go mod files and download dependencies
COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Build the Go binary
RUN go build -o producer/producer ./producer

# Expose HTTP port
EXPOSE 8080

COPY wait-for-it.sh ./
RUN chmod +x wait-for-it.sh

# Start the app
CMD ["./wait-for-it.sh", "kafka:9092", "--", "./producer/producer"]
